### ISSUE TITLE
optgroups+search filter activated+rightAll moves filtered options as well

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#98]
Hello,

just found out, if you use optgroups and filter the left side and then click on "RightAll" to move all remaining elements to the right side, the hidden (filtered) elements are moved as well.

I also found the place where the fix should probably be made and will propose a pull request.

**Comment by crlcu** [comment]
Hi,
It will be so nice if you can create a pull request with a fix.

Thanks

**Comment by danowar2k** [comment]
Done. Hope that helps.

**Comment by gtrdblt** [comment]
Hi, 

The bug also occurs if you select multiple items (filtered) using the upper case key with up/down arrows on your keyboard, then using the move right arrow.

**Comment by danowar2k** [comment]
I'll have something that will fix this in my big contribution.

**Comment by tiagomoucho3** [comment]
Hello,

As of version 2.5.6/2.5.7 (don't know if earlier) this issue is back. I noticed it moves the hidden option inside an optgroup even if wrapped in a span tag.
